name: Cripto Discord Bot

on:    
  repository_dispatch:
    types: [CriptoDiscordBot-Dispatch]

jobs:
   
  job:
    name: Run Action
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Npm Install CI
      run: npm ci

    - name: Run Discord.js
      run: WEBHOOK=${{ github.event.client_payload.webhook }} node Discord.js