name: Cripto Discord Bot

on:
  push:
    branches: [ main ]
    
  schedule: 
   # Cada 5 minutos. Igual ni funciona 🤷‍♂️
   - cron: '*/5 * * * *' 
   
  repository_dispatch:
    types: [CriptoDiscordBot-Dispatch]

  workflow_dispatch:

jobs:
   
  job:
    name: Run Action
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run Index.js
      run: node index.js